apiVersion: v1
kind: Secret
metadata:
  name: otc-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud.conf: |
    [Global]
    auth-url={{ .Values.otc.authUrl }}
    username={{ .Values.otc.username }}
    password={{ .Values.otc.password }}
    tenant-name={{ .Values.otc.tenantName }}
    domain-name={{ .Values.otc.domainName }}
    region={{ .Values.otc.region }}

    [LoadBalancer]
    subnet-id={{ .Values.otc.elb.subnetId }}
    floating-network-id={{ .Values.otc.elb.floatingNetworkId }}
    network-id={{ .Values.otc.elb.networkId }}
    create-monitor=true
    monitor-delay=5s
    monitor-timeout=3s
    monitor-max-retries=3

    [Networking]
    public-network-name=admin_external_net
