{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: swiss-otc-cloud-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: swiss-otc-ccm
type: Opaque
stringData:
  cloud.conf: |
    auth:
      auth_url: {{ .Values.cloudConfig.auth.authUrl }}
      username: {{ .Values.cloudConfig.auth.username }}
      password: {{ .Values.cloudConfig.auth.password | quote }}
      project_name: {{ .Values.cloudConfig.auth.projectName }}
      project_id: {{ .Values.cloudConfig.auth.projectId }}
      user_domain_name: {{ .Values.cloudConfig.auth.userDomainName }}
    region: {{ .Values.cloudConfig.region }}
    network:
      vpc_id: {{ .Values.cloudConfig.network.vpcId }}
      subnet_id: {{ .Values.cloudConfig.network.subnetId }}
      network_id: {{ .Values.cloudConfig.network.networkId }}
    loadbalancer:
      availability_zones:
      {{- range .Values.cloudConfig.loadbalancer.availabilityZones }}
        - {{ . }}
      {{- end }}
    metadata:
      cluster_id: {{ .Values.cloudConfig.metadata.clusterId }}
{{- end }}
