apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-bench
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Wolfslight-Forgehouse/rke2-sotc-cloud-manager
    targetRevision: main
    path: deploy/k8s/security
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
