apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: infrastructure
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.3.4
    helm:
      parameters:
        - name: admissionController.replicas
          value: "1"
        - name: backgroundController.enabled
          value: "true"
        - name: cleanupController.enabled
          value: "true"
        - name: reportsController.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
